### ISSUE TITLE
 add parameters `frame shift` & `frame length `

### ISSUE THREAD

**Issue by lsq357** [wiseman/py-webrtcvad#12]
How can I set parameters `frame shift` & `frame length`?
example.py  [line 53](https://github.com/wiseman/py-webrtcvad/blob/6ba97cdb84bfe1f6ca24bc94088ff54ab3621117/example.py#L53) and [line 56](https://github.com/wiseman/py-webrtcvad/blob/6ba97cdb84bfe1f6ca24bc94088ff54ab3621117/example.py#L56)
In my opinion, the `n` represents `fram length` and the `duration` represents `frame shift`,
but when I change
`n = int(sample_rate * (frame_duration_ms / 1000.0) * 4)`, it raises the `webrtcvad.Error`

**Comment by wiseman** [comment]
webrtc's VAD only works with frames that are 10 ms, 20 ms or 30 ms  long. The sample rate must be 8000, 16000, 32000 or 48000 Hz. The sample width must be 16 bits. Data that does not fit these restrictions will cause an error.

The line of code you reference is calculating the number of bytes in a frame. E.g. 10 ms of audio recorded at 16000 samples/second, where each sample is 2 bytes (that's there the `* 2` comes from) would be 16000 * (10 / 1000.0) * 2 = 320 bytes.

So the only way you can change the `frame_length` is by changing the frame duration (10, 20 or 30 ms) or sample rate (8000, 16000, 32000, or 48000).

I'm not sure what you mean by `frame_shift`.  `duration` in that function is really just the frame width in seconds instead of milliseconds.

**Comment by sxqqslf** [comment]
@wiseman frame_shift means the shift between two adjacent frames, e.g. the length of frame is 20ms, and the first frame is from 15ms to 35ms, if the frame_shift is 8ms, then the next frame is from 23ms to 43ms, why do this? Because the wave signal is consecutive, we want to keep the continuity of the original signal and be smooth. So I also wonder why webrtc does's not consider this parameter, thanks!
