### ISSUE TITLE
how to save time stamps of the chunks generated with the file name of that chunk

### ISSUE THREAD

**Issue by sagar2226** [wiseman/py-webrtcvad#27]

**Comment by bluemonk482** [comment]
Ditto

**Comment by wiseman** [comment]
I'm going to assume you're talking about adding this functionality to [example.py](https://github.com/wiseman/py-webrtcvad/blob/f369cdfde307f736be245d4ccea761e3f27468ea/example.py).

See how at [line 127](https://github.com/wiseman/py-webrtcvad/blob/f369cdfde307f736be245d4ccea761e3f27468ea/example.py#L127) the code in the `vad_collector` function references `frame.timestamp`?  You just need to change that function so that whenever it `yield`s audio data, it yields the data as well as the timestamp of the first voiced frame.  E.g. `yield voiced_frames[0].timestamp, b''.join([f.bytes for f in voiced_frames])`.

Then at [line 151](https://github.com/wiseman/py-webrtcvad/blob/f369cdfde307f736be245d4ccea761e3f27468ea/example.py#L151) the `segment` variable will actually hold a tuple `(timestamp, audio_data`).  You could change the code to look something like this:

```
    for i, seg in enumerate(segments):
        timestamp, segment = seg
        path = 'chunk-%002d-%s.wav' % (i, timestamp)
```

**Comment by sagar2226** [comment]
Thanks for your help.
I do have another requirement. The chunks generated should be no more than 9 seconds. how can i add this into the code.

Thanks in advance
