### ISSUE TITLE
I can not validate a chunk in the size of 1024

### ISSUE THREAD

**Issue by luisdemarchi** [wiseman/py-webrtcvad#30]
If you get your test files with whatever audio I'm generating, everything works. Each chunk of his was in the "size" of 480 (variable n). If you put any other value outside of this, the application receives the following error:

```
chunk = file.read(960)
>>> vad.is_speech(chunk, 8000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/webrtcvad.py", line 27, in is_speech
    return _webrtcvad.process(self._vad, sample_rate, buf, length)
webrtcvad.Error: Error while processing frame
```

**Comment by wiseman** [comment]
As the README mentions, "The WebRTC VAD only accepts 16-bit mono PCM audio, sampled at 8000, 16000, 32000 or 48000 Hz. A frame must be either 10, 20, or 30 ms in duration."

For example, if your sample rate is 16000 Hz, then the only allowed frame/chunk sizes are 16000 * ({10,20,30} / 1000) = 160, 320 or 480 samples. Since each sample is 2 bytes (16 bits), the only allowed frame/chunk sizes are 320, 640, or 960 bytes.

This is a restriction of the underlying webrtc library, not the python wrapper.

**Comment by Atul-Anand-Jha** [comment]
> As the README mentions, "The WebRTC VAD only accepts 16-bit mono PCM audio, sampled at 8000, 16000, 32000 or 48000 Hz. A frame must be either 10, 20, or 30 ms in duration."
> 
> For example, if your sample rate is 16000 Hz, then the only allowed frame/chunk sizes are 16000 * ({10,20,30} / 1000) = 160, 320 or 480 samples. Since each sample is 2 bytes (16 bits), the only allowed frame/chunk sizes are 320, 640, or 960 bytes.
> 
> This is a restriction of the underlying webrtc library, not the python wrapper.

How can i use more than just 1 Channels ??
If i use CHANNELS >= 2 ; i get the same error.

What other things do i need to change, suppose if i am using 8 channels audio input ?

**Comment by wiseman** [comment]
You could mix down multiple channels into a single channel, then run that channel through the VAD.  Or you could run each channel through VAD, in turn.

**Comment by naosk8** [comment]
maybe this one is already solved, but if anyone uses ffmpeg to extract audio from movie you can use `-ac 1` option to get mono audio data. just a small tips.
